// Code generated by go-swagger; DO NOT EDIT.

package k8s_monitoring_tool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// GetV1alpha1PodsLogURL generates an URL for the get v1alpha1 pods log operation
type GetV1alpha1PodsLogURL struct {
	ContainerName string
	Namespace     string
	PodName       string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetV1alpha1PodsLogURL) WithBasePath(bp string) *GetV1alpha1PodsLogURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetV1alpha1PodsLogURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetV1alpha1PodsLogURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1alpha1/pods/log"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/kmt"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	containerNameQ := o.ContainerName
	if containerNameQ != "" {
		qs.Set("containerName", containerNameQ)
	}

	namespaceQ := o.Namespace
	if namespaceQ != "" {
		qs.Set("namespace", namespaceQ)
	}

	podNameQ := o.PodName
	if podNameQ != "" {
		qs.Set("podName", podNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetV1alpha1PodsLogURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetV1alpha1PodsLogURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetV1alpha1PodsLogURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetV1alpha1PodsLogURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetV1alpha1PodsLogURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetV1alpha1PodsLogURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
