// Code generated by go-swagger; DO NOT EDIT.

package k8s_monitoring_tool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"k8s-monitoring-tool/models"
)

// NewPutV1PodParams creates a new PutV1PodParams object
// no default values defined in spec.
func NewPutV1PodParams() PutV1PodParams {

	return PutV1PodParams{}
}

// PutV1PodParams contains all the bound params for the put v1 pod operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutV1Pod
type PutV1PodParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*New Pod deployment request body.
	  In: body
	*/
	PodDeployment *models.PodDeployment
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutV1PodParams() beforehand.
func (o *PutV1PodParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PodDeployment
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("podDeployment", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.PodDeployment = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
