// Code generated by go-swagger; DO NOT EDIT.

package k8s_monitoring_tool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutV1alpha1PodsHandlerFunc turns a function with the right signature into a put v1alpha1 pods handler
type PutV1alpha1PodsHandlerFunc func(PutV1alpha1PodsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutV1alpha1PodsHandlerFunc) Handle(params PutV1alpha1PodsParams) middleware.Responder {
	return fn(params)
}

// PutV1alpha1PodsHandler interface for that can handle valid put v1alpha1 pods params
type PutV1alpha1PodsHandler interface {
	Handle(PutV1alpha1PodsParams) middleware.Responder
}

// NewPutV1alpha1Pods creates a new http.Handler for the put v1alpha1 pods operation
func NewPutV1alpha1Pods(ctx *middleware.Context, handler PutV1alpha1PodsHandler) *PutV1alpha1Pods {
	return &PutV1alpha1Pods{Context: ctx, Handler: handler}
}

/* PutV1alpha1Pods swagger:route PUT /v1alpha1/pods k8s-monitoring-tool putV1alpha1Pods

Update a pod configuration running in the k8s cluster

For example:
```
PUT /api/kmt/v1/pod
```

Sample request body will be:

```
{
  "name": "apache-cassandra",
  "namespace": "default",
  "replicas": "5",
  "image": "ccas-apache:2.5"
}
```


*/
type PutV1alpha1Pods struct {
	Context *middleware.Context
	Handler PutV1alpha1PodsHandler
}

func (o *PutV1alpha1Pods) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutV1alpha1PodsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
