swagger: "2.0"
info:
  title: Kubernetes Monitoring Tool (KMT)
  description: KMT provides rest endpoints to help clients to get monitoring data from a Kubernetes cluster.
  version: "1.0.0"

basePath: /api/kmt
schemes:
  - http

paths:
  /v1/pods:
    get:
      summary: Gets all pods statistics running in the k8s cluster
      tags:
        - k8s-monitoring-tool
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: query
          name: namespace
          type: string
          required: false
          description: Pass if pods status for a specific namespace is desired; otherwise all pods across all namespaces are returned.
      description: |
        For example:
        ```
        GET /api/kmt/v1/pods
        GET /api/kmt/v1/pods?namespace=databricks
        ```

        Returns list of pods with their status:
        ```
        [
          {
            "name": "pod-1",
            "status": {
              "phase": "Running",
              "description": "Pod is running",
              "podIp": "192.1.1.1",
              "hostIp": "string"
            }
          },
          {
            "name": "pod-2",
            "status": {
              "phase": "Pending",
              "description": "Pending due to lack of resources",
              "podIp": "",
              "hostIp": ""
            }
          },
          ...
        ]
        ```
      responses:
        '200':
          description: Fetching of all pod status is successful.
          schema:
            $ref: "#/definitions/Pods"
        '500':
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"

  /v1/pod:
    put:
      summary: Update a pod configuration running in the k8s cluster
      tags:
        - k8s-monitoring-tool
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: PodDeployment
          description: New Pod deployment request body.
          schema:
            $ref: '#/definitions/PodDeployment'
      description: |
        For example:
        ```
        PUT /api/kmt/v1/pod
        ```

        Sample request body will be:

        ```
        {
          "name": "apache-cassandra",
          "replicas": "5",
          "image": "ccas-apache:2.5"
        }
        ```
      responses:
        '200':
          description: Pod deployment updated successfully.
          schema:
            $ref: '#/definitions/PodDeployment'
        '400':
          description: Bad Request, Unable to update pod deployment.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error.
          schema:
            $ref: '#/definitions/Error'

definitions:
  Pod:
    type: object
    description: A pod
    required:
      - name
      - status
    properties:
      name:
        type: string
        description: Pod name
      status:
        type: object
        description: Pod status
        $ref: "#/definitions/PodStatus"
  PodStatus:
    type: object
    description: A pod
    required:
      - phase
      - description
      - podIp
      - hostIp
    properties:
      phase:
        type: string
        description: The phase of a Pod is a simple, high-level summary of where the Pod is in its lifecycle (Pending, Running, Failed, Unknown)
      description:
        type: string
        description: Details about why the pod is in this condition.
      podIp:
        type: string
        description: IP address allocated to the pod
      hostIp:
        type: string
        description: IP address of the host to which the pod is assigned
  PodDeployment:
    type: object
    description: A pod deployment to update
    required:
      - name
      - replicas
      - image
    properties:
      name:
        type: string
        description: Provide the name of the pod deployment.
      replicas:
        type: string
        description: Provide the number of replicas to modify.
      image:
        type: string
        description: Provide the new image name, version.
  Pods:
    type: array
    description: Array of pod items
    items:
      $ref: "#/definitions/Pod"
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string