// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Kubernetes Monitoring Tool (KMT)
//
//  KMT provides rest endpoints to help clients to get monitoring data from a Kubernetes cluster.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/kmt
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
