// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PodDeployment A pod deployment to update
//
// swagger:model PodDeployment
type PodDeployment struct {

	// Label key used for pods scheduling anti-affinity rule.
	AffinityKey string `json:"affinityKey,omitempty"`

	// Comma separated label selector key values for pods scheduling anti-affinity rule.
	AffinityValues string `json:"affinityValues,omitempty"`

	// Provide the new image name, version.
	Image string `json:"image,omitempty"`

	// Provide the name of the pod deployment.
	Name string `json:"name,omitempty"`

	// Provide the number of replicas to modify.
	Replicas string `json:"replicas,omitempty"`
}

// Validate validates this pod deployment
func (m *PodDeployment) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PodDeployment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodDeployment) UnmarshalBinary(b []byte) error {
	var res PodDeployment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
